package mrg.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import mrg.data.CostElement;
import mrg.data.LineItem;

/**
 * Class _BudgetYear was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BudgetYear extends CayenneDataObject {

    public static final String LINE_ITEM_PROPERTY = "lineItem";
    public static final String QTY_COST_ELEMENTS_PROPERTY = "qtyCostElements";
    public static final String TC_COST_ELEMENTS_PROPERTY = "tcCostElements";
    public static final String UC_COST_ELEMENTS_PROPERTY = "ucCostElements";

    public static final String ID_PK_COLUMN = "id";

    public void setLineItem(LineItem lineItem) {
        setToOneTarget("lineItem", lineItem, true);
    }

    public LineItem getLineItem() {
        return (LineItem)readProperty("lineItem");
    }


    public void addToQtyCostElements(CostElement obj) {
        addToManyTarget("qtyCostElements", obj, true);
    }
    public void removeFromQtyCostElements(CostElement obj) {
        removeToManyTarget("qtyCostElements", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CostElement> getQtyCostElements() {
        return (List<CostElement>)readProperty("qtyCostElements");
    }


    public void addToTcCostElements(CostElement obj) {
        addToManyTarget("tcCostElements", obj, true);
    }
    public void removeFromTcCostElements(CostElement obj) {
        removeToManyTarget("tcCostElements", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CostElement> getTcCostElements() {
        return (List<CostElement>)readProperty("tcCostElements");
    }


    public void addToUcCostElements(CostElement obj) {
        addToManyTarget("ucCostElements", obj, true);
    }
    public void removeFromUcCostElements(CostElement obj) {
        removeToManyTarget("ucCostElements", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CostElement> getUcCostElements() {
        return (List<CostElement>)readProperty("ucCostElements");
    }


}
