package mrg.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import mrg.data.BudgetYear;
import mrg.data.Item;

/**
 * Class _LineItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LineItem extends CayenneDataObject {

    public static final String NUMBER_PROPERTY = "number";
    public static final String BUDGET_YEARS_PROPERTY = "budgetYears";
    public static final String ITEMS_PROPERTY = "items";

    public static final String ID_PK_COLUMN = "id";

    public void setNumber(Integer number) {
        writeProperty("number", number);
    }
    public Integer getNumber() {
        return (Integer)readProperty("number");
    }

    public void addToBudgetYears(BudgetYear obj) {
        addToManyTarget("budgetYears", obj, true);
    }
    public void removeFromBudgetYears(BudgetYear obj) {
        removeToManyTarget("budgetYears", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BudgetYear> getBudgetYears() {
        return (List<BudgetYear>)readProperty("budgetYears");
    }


    public void addToItems(Item obj) {
        addToManyTarget("items", obj, true);
    }
    public void removeFromItems(Item obj) {
        removeToManyTarget("items", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Item> getItems() {
        return (List<Item>)readProperty("items");
    }


}
